name: Build UltraBot to Windows EXE and Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name=UltraBot `
          --add-data "bot/automation;automation" `
          --add-data "bot/gui;gui" `
          --add-data "bot/utils;utils" `
          --hidden-import=PyQt5 `
          --hidden-import=selenium `
          --hidden-import=webdriver_manager `
          --hidden-import=Eel `
          --hidden-import=requests `
          --hidden-import=dotenv `
          --hidden-import=browser_cookie3 `
          --additional-hooks-dir=. `
          bot/main.py
    
    - name: Install NSIS
      run: |
        choco install nsis -y
        refreshenv
    
    - name: Create Installer
      run: |
        echo !define APP_NAME "UltraBot" > installer.nsi
        echo !define EXEC_NAME "UltraBot.exe" >> installer.nsi
        echo !define VERSION "1.0.0" >> installer.nsi
        echo !include "MUI2.nsh" >> installer.nsi
        echo Name "${APP_NAME} ${VERSION}" >> installer.nsi
        echo OutFile "${APP_NAME}-Setup.exe" >> installer.nsi
        echo InstallDir "$PROGRAMFILES\${APP_NAME}" >> installer.nsi
        echo !insertmacro MUI_PAGE_DIRECTORY >> installer.nsi
        echo !insertmacro MUI_PAGE_INSTFILES >> installer.nsi
        echo !insertmacro MUI_LANGUAGE "English" >> installer.nsi
        echo Section >> installer.nsi
        echo SetOutPath "$INSTDIR" >> installer.nsi
        echo File "dist\${EXEC_NAME}" >> installer.nsi
        echo CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${EXEC_NAME}" >> installer.nsi
        echo SectionEnd >> installer.nsi
        makensis installer.nsi
    
    - name: Upload EXE and Installer as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ultrabot-windows-app
        path: |
          dist/*.exe
          *.exe