name: Build UltraBot to Windows EXE and Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Update requirements.txt
      run: |
        (Get-Content requirements.txt) -replace 'PyQt5-Qt5==5.15.14', 'PyQt5-Qt5==5.15.2' | Set-Content requirements.txt
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
      continue-on-error: true
    
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name=UltraBot `
          --add-data "automation;automation" `
          --add-data "gui;gui" `
          --add-data "utils;utils" `
          --hidden-import=PyQt5 `
          --hidden-import=selenium `
          --hidden-import=webdriver_manager `
          --hidden-import=Eel `
          --hidden-import=requests `
          --hidden-import=dotenv `
          --hidden-import=browser_cookie3 `
          --additional-hooks-dir=. `
          --log-level DEBUG `
          main.py
    
    - name: Check if EXE was created
      run: |
        if (Test-Path dist/UltraBot.exe) {
          echo "EXE file created successfully"
        } else {
          echo "EXE file creation failed"
          exit 1
        }
    
    - name: Install NSIS
      run: |
        choco install nsis -y --ignore-checksums
      continue-on-error: true
    
    - name: Create Installer
      run: |
        @'
        !define APP_NAME "UltraBot"
        !define EXEC_NAME "UltraBot.exe"
        !define VERSION "1.0.0"
        !include "MUI2.nsh"
        Name "${APP_NAME} ${VERSION}"
        OutFile "${APP_NAME}-Setup.exe"
        InstallDir "$PROGRAMFILES\${APP_NAME}"
        !insertmacro MUI_PAGE_DIRECTORY
        !insertmacro MUI_PAGE_INSTFILES
        !insertmacro MUI_LANGUAGE "English"
        Section
          SetOutPath "$INSTDIR"
          File "dist\${EXEC_NAME}"
          CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${EXEC_NAME}"
        SectionEnd
        '@ | Out-File -Encoding ASCII installer.nsi
        
        makensis /V4 installer.nsi
    
    - name: Upload EXE and Installer as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ultrabot-windows-app
        path: |
          dist/*.exe
          *.exe